### ISSUE TITLE
Probleme unter Ubuntu 14.04

### ISSUE THREAD

**Issue by weidnerd** [RootService/certbot-wrapper#1]
Servus!

Ich habe schon einige Änderungen vorgenommen, um den wrapper unter Ubuntu laufen zu lassen:

'CUR_DATE_F="`/bin/date -u +%F`"
CUR_DATE_S="`/bin/date -u +%s`"
...
if [ "`/usr/bin/openssl version | /usr/bin/cut -d " " -f 2 | /usr/bin/cut -c 1-5`" = "1.0.2" ]
...
sed liegt auf /bin/sed'

Es funtioniert leider noch nicht: 

'+ /bin/echo 
+ setup_subdomain daniel-weidner.de daniel@weidner.bayern
+ local DOMAIN=daniel-weidner.de
+ local SUBDOMAIN=daniel@weidner.bayern
+ local EMAIL=
+ [ ! -d /srv/ssl/daniel-weidner.de/daniel@weidner.bayern ]
+ /bin/mkdir -p /srv/ssl/daniel-weidner.de/daniel@weidner.bayern
+ cd /srv/ssl/daniel-weidner.de
+ create_requests daniel-weidner.de daniel@weidner.bayern
+ local DOMAIN=daniel-weidner.de
+ local SUBDOMAIN=daniel@weidner.bayern
+ local EMAIL=
+ /bin/cat
+ **/bin/sed -e s|__SUBDOMAIN__|daniel@weidner.bayern|g -e s|__DOMAIN__|daniel-weidner.de|g -e s|__EMAIL__||g -i  /srv/ssl/daniel-weidner.de/daniel@weidner.bayern
/openssl.conf
/bin/sed: kann  nicht lesen: Datei oder Verzeichnis nicht gefunden**
+ /usr/bin/openssl req -new -batch -sha384 -config /srv/ssl/daniel-weidner.de/daniel@weidner.bayern/openssl.conf -out /srv/ssl/daniel-weidner.de/daniel@weidner.
bayern/request.00.ecc.csr -key /srv/ssl/daniel-weidner.de/_privkey.00.ecc.key.enc -passin file:/srv/ssl/daniel-weidner.de/_privkey.00.ecc.pwd
problems making Certificate Request
140607577048728:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:a_mbstr.c:151:minsize=1
+ /usr/bin/openssl req -new -batch -sha384 -config /srv/ssl/daniel-weidner.de/daniel@weidner.bayern/openssl.conf -out /srv/ssl/daniel-weidner.de/daniel@weidner.
bayern/request.00.rsa.csr -key /srv/ssl/daniel-weidner.de/_privkey.00.rsa.key.enc -passin file:/srv/ssl/daniel-weidner.de/_privkey.00.rsa.pwd
problems making Certificate Request
140242135717528:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:a_mbstr.c:151:minsize=1
+ /usr/bin/openssl req -new -batch -sha384 -config /srv/ssl/daniel-weidner.de/daniel@weidner.bayern/openssl.conf -out /srv/ssl/daniel-weidner.de/daniel@weidner.
bayern/request.00.ecc.csr -key /srv/ssl/daniel-weidner.de/_privkey.00.ecc.key.enc -passin file:/srv/ssl/daniel-weidner.de/_privkey.00.ecc.pwd
problems making Certificate Request
140068704171672:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:a_mbstr.c:151:minsize=1
+ /usr/bin/openssl req -new -batch -sha384 -config /srv/ssl/daniel-weidner.de/daniel@weidner.bayern/openssl.conf -out /srv/ssl/daniel-weidner.de/daniel@weidner.
bayern/request.00.rsa.csr -key /srv/ssl/daniel-weidner.de/_privkey.00.rsa.key.enc -passin file:/srv/ssl/daniel-weidner.de/_privkey.00.rsa.pwd
problems making Certificate Request
140185604646552:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:a_mbstr.c:151:minsize=1
+ return
+ **create_acme_certificates daniel-weidner.de daniel@weidner.bayern**
+ **local DOMAIN=daniel-weidner.de**
+ **local SUBDOMAIN=daniel@weidner.bayern**
+ **local EMAIL=**
+ /usr/bin/certbot certonly --text --quiet --agree-tos --config-dir /srv/ssl/acme --csr /srv/ssl/daniel-weidner.de/daniel@weidner.bayern/request.00.ecc.csr --ke
y-path /srv/ssl/daniel-weidner.de/_privkey.00.ecc.key.enc --cert-path /srv/ssl/daniel-weidner.de/daniel@weidner.bayern/cert.00.ecc.crt --chain-path /srv/ssl/dan
iel-weidner.de/daniel@weidner.bayern/chain.00.ecc.crt --fullchain-path /srv/ssl/daniel-weidner.de/daniel@weidner.bayern/fullchain.00.ecc.crt --webroot --webroot
-path /srv/www/acme --domain daniel@weidner.bayern.daniel-weidner.de --domain daniel-weidner.de --email
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...`

Anscheinend wird irgendwo Subdomain und eMail-Adresse vertauscht!

Wo kann ich ansetzen?

Daniel

**Comment by JoeUser78** [comment]
Moin Daniel,

Du hast in https://github.com/RootService/certbot-wrapper/blob/master/certbot-wrapper.sh#L353-L357 einen Fehler eingebaut.

Kannst Du mir Deine Version zukommen lassen, sobald sie funktioniert, dann kann ich schauen ob ich meine Version um etwas Linux-Kompatibilität erweitern.

Danke und Gruss,
Markus

**Comment by weidnerd** [comment]
Hi!

Ich habe das Problem gefunden. Wenn ich keine Subdomain angebe, funktiert es nicht. Beim Aufruf von setup_subdomain fehlt dann ein Argument. 

Ich habe noch ein anderes Problem gefunden:
In https://github.com/RootService/certbot-wrapper/blob/master/certbot-wrapper.sh#L401-L412 ist das webroot-Verzeichnis falsch. Es verweist auf ${DIRWWW}/acme, was aber unterhalb des jeweiligen Webroots (z.B. ${DIRWWW}/WEI_typo3) liegt. 

Dabei kommt dann sowas raus:
`+ /usr/bin/certbot certonly --text --quiet --agree-tos --config-dir /srv/ssl/acme --csr /srv/ssl/daniel-weidner.de/typo3/request
.00.rsa.csr --key-path /srv/ssl/daniel-weidner.de/_privkey.00.rsa.key.enc --cert-path /srv/ssl/daniel-weidner.de/typo3/cert.00.r
sa.crt --chain-path /srv/ssl/daniel-weidner.de/typo3/chain.00.rsa.crt --fullchain-path /srv/ssl/daniel-weidner.de/typo3/fullchai
n.00.rsa.crt --webroot --webroot-path /srv/www/acme --domain typo3.daniel-weidner.de --domain daniel-weidner.de --email daniel@w
eidner.bayern
Failed authorization procedure. typo3.daniel-weidner.de (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://typo3.daniel-weidner.de/.well-known/acme-challenge/AhxMKFQX9O1M3KJfXt540yLM-HbHV7cWw
12wSrc05Mw: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">`

Da in dem Beispiel typo3.daniel-weidner.de in /srv/www/WEI.typo3 liegt, kann die Authorisation nicht klappen.

Daniel

**Comment by JoeUser78** [comment]
Da fehlt Dir die notwendige Anpassung der Apache Konfiguration aus der README https://github.com/RootService/certbot-wrapper (AliasMatch)
